IPPAPI(IppStatus, ippsCopy_32f,  (const Ipp32f*  pSrc, Ipp32f*  pDst, int len))
IPPAPI(IppStatus, ippsMove_32f,  (const Ipp32f*  pSrc, Ipp32f*  pDst, int len))
IPPAPI(IppStatus, ippsSet_32f,  (Ipp32f  val, Ipp32f*  pDst, int len))
IPPAPI(IppStatus, ippsZero_32f,  (Ipp32f*  pDst, int len))
IPPAPI(IppStatus, ippsTriangle_32f,  (Ipp32f*  pDst, int len, Ipp32f magn, Ipp32f rFreq, Ipp32f asym, Ipp32f* pPhase))
IPPAPI(IppStatus, ippsVectorJaehne_32f, (Ipp32f* pDst, int len, Ipp32f magn))
IPPAPI(IppStatus, ippsVectorSlope_32f, (Ipp32f* pDst, int len, Ipp32f offset, Ipp32f slope))
IPPAPI(IppStatus, ippsAddC_32f,       (const Ipp32f*  pSrc, Ipp32f  val, Ipp32f*  pDst,    int len))
IPPAPI(IppStatus, ippsAddProduct_32f,        (const Ipp32f*  pSrc1, const Ipp32f*  pSrc2, Ipp32f*  pSrcDst, int len))
IPPAPI(IppStatus, ippsMulC_32f,         (const Ipp32f*  pSrc, Ipp32f  val, Ipp32f*  pDst,    int len))
IPPAPI(IppStatus, ippsSubC_32f,       (const Ipp32f*  pSrc, Ipp32f  val, Ipp32f*  pDst,    int len))
IPPAPI(IppStatus, ippsSubCRev_32f,       (const Ipp32f*  pSrc, Ipp32f  val, Ipp32f*  pDst,    int len))
IPPAPI(IppStatus, ippsDivC_32f,      (const Ipp32f*  pSrc, Ipp32f  val, Ipp32f*  pDst,    int len))
IPPAPI(IppStatus, ippsSumLn_32f,    (const Ipp32f* pSrc, int len, Ipp32f* pSum))
IPPAPI(IppStatus, ippsArctan_32f,   (const Ipp32f* pSrc, Ipp32f* pDst,    int len))
IPPAPI(IppStatus, ippsNormalize_32f,      (const Ipp32f*  pSrc, Ipp32f* pDst,     int len, Ipp32f  vSub, Ipp32f vDiv))
IPPAPI(IppStatus, ippsMagnitude_32f,      (const Ipp32f*  pSrcRe, const Ipp32f* pSrcIm, Ipp32f* pDst, int len))
IPPAPI(IppStatus, ippsPhase_32f,     (const Ipp32f* pSrcRe, const Ipp32f* pSrcIm, Ipp32f* pDst, int len))
IPPAPI(IppStatus, ippsPowerSpectr_32f,    (const Ipp32f* pSrcRe, const Ipp32f* pSrcIm, Ipp32f* pDst, int len))
IPPAPI(IppStatus, ippsThreshold_LT_32f,    (const Ipp32f*  pSrc, Ipp32f*  pDst, int len, Ipp32f level))
IPPAPI(IppStatus, ippsThreshold_GT_32f,    (const Ipp32f*  pSrc, Ipp32f*  pDst, int len, Ipp32f level))
IPPAPI(IppStatus, ippsThreshold_LTAbs_32f,   (const Ipp32f* pSrc, Ipp32f *pDst, int len, Ipp32f level))
IPPAPI(IppStatus, ippsThreshold_GTAbs_32f,   (const Ipp32f* pSrc, Ipp32f *pDst, int len, Ipp32f level))
IPPAPI(IppStatus, ippsThreshold_LTAbsVal_32f,   (const Ipp32f* pSrc, Ipp32f *pDst, int len, Ipp32f level, Ipp32f value))
IPPAPI(IppStatus, ippsThreshold_LTVal_32f,    (const Ipp32f*  pSrc, Ipp32f*  pDst, int len, Ipp32f level, Ipp32f  value))
IPPAPI(IppStatus, ippsThreshold_GTVal_32f,    (const Ipp32f*  pSrc, Ipp32f*  pDst, int len, Ipp32f level, Ipp32f  value))
IPPAPI(IppStatus, ippsThreshold_LTValGTVal_32f,   (const Ipp32f* pSrc, Ipp32f* pDst, int len, Ipp32f levelLT, Ipp32f valueLT, Ipp32f levelGT, Ipp32f valueGT))
IPPAPI(IppStatus, ippsThreshold_LTInv_32f,    (const Ipp32f*  pSrc, Ipp32f*  pDst, int len, Ipp32f level))
IPPAPI(IppStatus, ippsCartToPolar_32f,  (const Ipp32f* pSrcRe, const Ipp32f* pSrcIm, Ipp32f* pDstMagn, Ipp32f* pDstPhase, int len))
IPPAPI(IppStatus, ippsPolarToCart_32f,  (const Ipp32f* pSrcMagn, const Ipp32f* pSrcPhase, Ipp32f* pDstRe, Ipp32f* pDstIm, int len))
IPPAPI(IppStatus, ippsFlip_32f,    (const Ipp32f*  pSrc, Ipp32f*  pDst, int len))
IPPAPI(IppStatus, ippsWinBartlett_32f,   (const Ipp32f*  pSrc, Ipp32f* pDst,     int len))
IPPAPI(IppStatus, ippsWinHann_32f,   (const Ipp32f* pSrc,  Ipp32f* pDst,     int len))
IPPAPI(IppStatus, ippsWinHamming_32f,   (const Ipp32f* pSrc,  Ipp32f*  pDst,    int len))
IPPAPI(IppStatus, ippsWinBlackman_32f,    (const Ipp32f* pSrc,  Ipp32f*  pDst,    int len, Ipp32f alpha))
IPPAPI(IppStatus, ippsWinBlackmanStd_32f,   (const Ipp32f*  pSrc, Ipp32f*  pDst,    int len))
IPPAPI(IppStatus, ippsWinBlackmanOpt_32f,   (const Ipp32f*  pSrc, Ipp32f*  pDst,    int len))
IPPAPI(IppStatus, ippsWinKaiser_32f,   (const Ipp32f*  pSrc, Ipp32f*  pDst,    int len, Ipp32f alpha))
IPPAPI(IppStatus, ippsSum_32f,         (const Ipp32f*  pSrc, int len, Ipp32f*  pSum, IppHintAlgorithm hint))
IPPAPI(IppStatus, ippsMin_32f, (const Ipp32f* pSrc, int len, Ipp32f* pMin))
IPPAPI(IppStatus, ippsMax_32f, (const Ipp32f* pSrc, int len, Ipp32f* pMax))
IPPAPI(IppStatus, ippsMinMax_32f, (const Ipp32f* pSrc, int len, Ipp32f* pMin, Ipp32f* pMax))
IPPAPI(IppStatus, ippsMinAbs_32f, (const Ipp32f* pSrc, int len, Ipp32f* pMinAbs))
IPPAPI(IppStatus, ippsMaxAbs_32f, (const Ipp32f* pSrc, int len, Ipp32f* pMaxAbs))
IPPAPI(IppStatus, ippsMinIndx_32f, (const Ipp32f* pSrc, int len, Ipp32f* pMin, int* pIndx))
IPPAPI(IppStatus, ippsMaxIndx_32f, (const Ipp32f* pSrc, int len, Ipp32f* pMax, int* pIndx))
IPPAPI(IppStatus, ippsMinMaxIndx_32f, (const Ipp32f* pSrc, int len, Ipp32f* pMin, int* pMinIndx, Ipp32f* pMax, int* pMaxIndx))
IPPAPI(IppStatus, ippsMean_32f,     (const Ipp32f*  pSrc, int len, Ipp32f*  pMean, IppHintAlgorithm hint))
IPPAPI(IppStatus, ippsStdDev_32f,       (const Ipp32f* pSrc, int len, Ipp32f* pStdDev, IppHintAlgorithm hint))
IPPAPI(IppStatus, ippsMeanStdDev_32f,       (const Ipp32f* pSrc, int len, Ipp32f* pMean, Ipp32f* pStdDev, IppHintAlgorithm hint))
IPPAPI(IppStatus, ippsNorm_Inf_32f,         (const Ipp32f*  pSrc, int len, Ipp32f* pNorm))
IPPAPI(IppStatus, ippsNorm_L1_32f,          (const Ipp32f*  pSrc, int len, Ipp32f* pNorm))
IPPAPI(IppStatus, ippsNorm_L2_32f,          (const Ipp32f*  pSrc, int len, Ipp32f* pNorm))
IPPAPI(IppStatus, ippsNormDiff_Inf_32f,         (const Ipp32f*  pSrc1, const Ipp32f*  pSrc2, int len, Ipp32f* pNorm))
IPPAPI(IppStatus, ippsNormDiff_L1_32f,          (const Ipp32f*  pSrc1, const Ipp32f*  pSrc2, int len, Ipp32f* pNorm))
IPPAPI(IppStatus, ippsNormDiff_L2_32f,          (const Ipp32f*  pSrc1, const Ipp32f*  pSrc2, int len, Ipp32f* pNorm))
IPPAPI(IppStatus, ippsDotProd_32f,          (const Ipp32f*  pSrc1, const Ipp32f*  pSrc2, int len, Ipp32f*  pDp))
IPPAPI(IppStatus, ippsMinEvery_32f, (const Ipp32f* pSrc1, const Ipp32f* pSrc2, Ipp32f* pDst, Ipp32u len))
IPPAPI(IppStatus, ippsMaxEvery_32f, (const Ipp32f* pSrc1, const Ipp32f* pSrc2, Ipp32f* pDst, Ipp32u len))
IPPAPI(IppStatus, ippsMaxOrder_32f, (const Ipp32f* pSrc, int len, int* pOrder))
IPPAPI(IppStatus, ippsSampleUp_32f,  (const Ipp32f*  pSrc, int  srcLen, Ipp32f*  pDst, int* pDstLen, int factor, int* pPhase))
IPPAPI(IppStatus, ippsSampleDown_32f,  (const Ipp32f*  pSrc, int  srcLen, Ipp32f*  pDst, int* pDstLen, int factor, int* pPhase))
IPPAPI(IppStatus, ippsFilterMedian_32f,   (const Ipp32f* pSrc, Ipp32f* pDst,    int len, int maskSize, const Ipp32f *pDlySrc, Ipp32f *pDlyDst, Ipp8u *pBuffer))
