_Mkl_Api(int,vsRngCauchy,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r,  const float a, const float b  ))
_Mkl_Api(int,vsRngUniform,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r,  const float a, const float b  ))
_Mkl_Api(int,vsRngGaussian,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r,  const float a, const float b  ))
_Mkl_Api(int,vsRngGaussianMV,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r,  const MKL_INT dimen,  const MKL_INT mstorage, const float *a,  const float *t ))
_Mkl_Api(int,vsRngExponential,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r,  const float a, const float b  ))
_Mkl_Api(int,vsRngLaplace,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r,  const float a, const float b  ))
_Mkl_Api(int,vsRngWeibull,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r,  const float a, const float b ,  const float c))
_Mkl_Api(int,vsRngRayleigh,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r,  const float a, const float b  ))
_Mkl_Api(int,vsRngLognormal,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r,  const float a, const float b ,  const float c,  const float d))
_Mkl_Api(int,vsRngGumbel,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r,  const float a, const float b  ))
_Mkl_Api(int,vsRngGamma,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r,  const float a, const float b ,  const float c))
_Mkl_Api(int,vsRngBeta,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r,  const float a, const float b ,  const float c,  const float d))
