float  cblas_sdot(const MKL_INT N, const float  *X, const MKL_INT incX, const float  *Y, const MKL_INT incY);
float  cblas_sdoti(const MKL_INT N, const float *X, const MKL_INT *indx, const float *Y);
float  cblas_snrm2(const MKL_INT N, const float *X, const MKL_INT incX);
float  cblas_sasum(const MKL_INT N, const float *X, const MKL_INT incX);
void cblas_sswap(const MKL_INT N, float *X, const MKL_INT incX, float *Y, const MKL_INT incY);
void cblas_scopy(const MKL_INT N, const float *X, const MKL_INT incX, float *Y, const MKL_INT incY);
void cblas_saxpy(const MKL_INT N, const float alpha, const float *X, const MKL_INT incX, float *Y, const MKL_INT incY);
void cblas_saxpby(const MKL_INT N, const float alpha, const float *X, const MKL_INT incX, const float beta, float *Y, const MKL_INT incY);
void cblas_saxpyi(const MKL_INT N, const float alpha, const float *X, const MKL_INT *indx, float *Y);
void cblas_sgthr(const MKL_INT N, const float *Y, float *X, const MKL_INT *indx);
void cblas_sgthrz(const MKL_INT N, float *Y, float *X, const MKL_INT *indx);
void cblas_ssctr(const MKL_INT N, const float *X, const MKL_INT *indx, float *Y);
void cblas_srotg(float *a, float *b, float *c, float *s);
void cblas_srotmg(float *d1, float *d2, float *b1, const float b2, float *P);
void cblas_srot(const MKL_INT N, float *X, const MKL_INT incX, float *Y, const MKL_INT incY, const float c, const float s);
void cblas_sroti(const MKL_INT N, float *X, const MKL_INT *indx, float *Y, const float c, const float s);
void cblas_srotm(const MKL_INT N, float *X, const MKL_INT incX, float *Y, const MKL_INT incY, const float *P);
void cblas_sscal(const MKL_INT N, const float alpha, float *X, const MKL_INT incX);
void cblas_sgemv(const  CBLAS_LAYOUT Layout, const  CBLAS_TRANSPOSE TransA, const MKL_INT M, const MKL_INT N, const float alpha, const float *A, const MKL_INT lda, const float *X, const MKL_INT incX, const float beta, float *Y, const MKL_INT incY);
void cblas_sgbmv(const  CBLAS_LAYOUT Layout, const  CBLAS_TRANSPOSE TransA, const MKL_INT M, const MKL_INT N, const MKL_INT KL, const MKL_INT KU, const float alpha, const float *A, const MKL_INT lda, const float *X, const MKL_INT incX, const float beta, float *Y, const MKL_INT incY);
void cblas_strmv(const  CBLAS_LAYOUT Layout, const  CBLAS_UPLO Uplo, const  CBLAS_TRANSPOSE TransA, const  CBLAS_DIAG Diag, const MKL_INT N, const float *A, const MKL_INT lda, float *X, const MKL_INT incX);
void cblas_stbmv(const  CBLAS_LAYOUT Layout, const  CBLAS_UPLO Uplo, const  CBLAS_TRANSPOSE TransA, const  CBLAS_DIAG Diag, const MKL_INT N, const MKL_INT K, const float *A, const MKL_INT lda, float *X, const MKL_INT incX);
void cblas_stpmv(const  CBLAS_LAYOUT Layout, const  CBLAS_UPLO Uplo, const  CBLAS_TRANSPOSE TransA, const  CBLAS_DIAG Diag, const MKL_INT N, const float *Ap, float *X, const MKL_INT incX);
void cblas_strsv(const  CBLAS_LAYOUT Layout, const  CBLAS_UPLO Uplo, const  CBLAS_TRANSPOSE TransA, const  CBLAS_DIAG Diag, const MKL_INT N, const float *A, const MKL_INT lda, float *X, const MKL_INT incX);
void cblas_stbsv(const  CBLAS_LAYOUT Layout, const  CBLAS_UPLO Uplo, const  CBLAS_TRANSPOSE TransA, const  CBLAS_DIAG Diag, const MKL_INT N, const MKL_INT K, const float *A, const MKL_INT lda, float *X, const MKL_INT incX);
void cblas_stpsv(const  CBLAS_LAYOUT Layout, const  CBLAS_UPLO Uplo, const  CBLAS_TRANSPOSE TransA, const  CBLAS_DIAG Diag, const MKL_INT N, const float *Ap, float *X, const MKL_INT incX);
void cblas_ssymv(const  CBLAS_LAYOUT Layout, const  CBLAS_UPLO Uplo, const MKL_INT N, const float alpha, const float *A, const MKL_INT lda, const float *X, const MKL_INT incX, const float beta, float *Y, const MKL_INT incY);
void cblas_ssbmv(const  CBLAS_LAYOUT Layout, const  CBLAS_UPLO Uplo, const MKL_INT N, const MKL_INT K, const float alpha, const float *A, const MKL_INT lda, const float *X, const MKL_INT incX, const float beta, float *Y, const MKL_INT incY);
void cblas_sspmv(const  CBLAS_LAYOUT Layout, const  CBLAS_UPLO Uplo, const MKL_INT N, const float alpha, const float *Ap, const float *X, const MKL_INT incX, const float beta, float *Y, const MKL_INT incY);
void cblas_sger(const  CBLAS_LAYOUT Layout, const MKL_INT M, const MKL_INT N, const float alpha, const float *X, const MKL_INT incX, const float *Y, const MKL_INT incY, float *A, const MKL_INT lda);
void cblas_ssyr(const  CBLAS_LAYOUT Layout, const  CBLAS_UPLO Uplo, const MKL_INT N, const float alpha, const float *X, const MKL_INT incX, float *A, const MKL_INT lda);
void cblas_sspr(const  CBLAS_LAYOUT Layout, const  CBLAS_UPLO Uplo, const MKL_INT N, const float alpha, const float *X, const MKL_INT incX, float *Ap);
void cblas_ssyr2(const  CBLAS_LAYOUT Layout, const  CBLAS_UPLO Uplo, const MKL_INT N, const float alpha, const float *X, const MKL_INT incX, const float *Y, const MKL_INT incY, float *A, const MKL_INT lda);
void cblas_sspr2(const  CBLAS_LAYOUT Layout, const  CBLAS_UPLO Uplo, const MKL_INT N, const float alpha, const float *X, const MKL_INT incX, const float *Y, const MKL_INT incY, float *A);
void cblas_sgemm(const  CBLAS_LAYOUT Layout, const  CBLAS_TRANSPOSE TransA, const  CBLAS_TRANSPOSE TransB, const MKL_INT M, const MKL_INT N, const MKL_INT K, const float alpha, const float *A, const MKL_INT lda, const float *B, const MKL_INT ldb, const float beta, float *C, const MKL_INT ldc);
void cblas_sgemmt(const  CBLAS_LAYOUT Layout, const  CBLAS_UPLO Uplo, const  CBLAS_TRANSPOSE TransA, const  CBLAS_TRANSPOSE TransB, const MKL_INT N, const MKL_INT K, const float alpha, const float *A, const MKL_INT lda, const float *B, const MKL_INT ldb, const float beta, float *C, const MKL_INT ldc);
void cblas_ssymm(const  CBLAS_LAYOUT Layout, const  CBLAS_SIDE Side, const  CBLAS_UPLO Uplo, const MKL_INT M, const MKL_INT N, const float alpha, const float *A, const MKL_INT lda, const float *B, const MKL_INT ldb, const float beta, float *C, const MKL_INT ldc);
void cblas_ssyrk(const  CBLAS_LAYOUT Layout, const  CBLAS_UPLO Uplo, const  CBLAS_TRANSPOSE Trans, const MKL_INT N, const MKL_INT K, const float alpha, const float *A, const MKL_INT lda, const float beta, float *C, const MKL_INT ldc);
void cblas_ssyr2k(const  CBLAS_LAYOUT Layout, const  CBLAS_UPLO Uplo, const  CBLAS_TRANSPOSE Trans, const MKL_INT N, const MKL_INT K, const float alpha, const float *A, const MKL_INT lda, const float *B, const MKL_INT ldb, const float beta, float *C, const MKL_INT ldc);
void cblas_strmm(const  CBLAS_LAYOUT Layout, const  CBLAS_SIDE Side, const  CBLAS_UPLO Uplo, const  CBLAS_TRANSPOSE TransA, const  CBLAS_DIAG Diag, const MKL_INT M, const MKL_INT N, const float alpha, const float *A, const MKL_INT lda, float *B, const MKL_INT ldb);
void cblas_strsm(const  CBLAS_LAYOUT Layout, const  CBLAS_SIDE Side, const  CBLAS_UPLO Uplo, const  CBLAS_TRANSPOSE TransA, const  CBLAS_DIAG Diag, const MKL_INT M, const MKL_INT N, const float alpha, const float *A, const MKL_INT lda, float *B, const MKL_INT ldb);
MKL_INT cblas_sgemm_pack_get_size(const  CBLAS_IDENTIFIER identifier, const MKL_INT M, const MKL_INT N, const MKL_INT K);
void cblas_sgemm_pack(const  CBLAS_LAYOUT Layout, const  CBLAS_IDENTIFIER identifier, const  CBLAS_TRANSPOSE Trans, const MKL_INT M, const MKL_INT N, const MKL_INT K, const float alpha, const float *src, const MKL_INT ld, float *dest);
void cblas_sgemm_compute(const  CBLAS_LAYOUT Layout, const MKL_INT TransA, const MKL_INT TransB, const MKL_INT M, const MKL_INT N, const MKL_INT K, const float *A, const MKL_INT lda, const float *B, const MKL_INT ldb, const float beta, float *C, const MKL_INT ldc);
void cblas_sgemm_free(float *dest);
