_Mkl_Api(int,viRngBernoulli,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r, const double a))
_Mkl_Api(int,viRngUniform,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r, const int a, const int b))
_Mkl_Api(int,viRngGeometric,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r, const double a))
_Mkl_Api(int,viRngBinomial,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r, const int  , const double  ))
_Mkl_Api(int,viRngMultinomial,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r, const int a, const int b, const double * c))
_Mkl_Api(int,viRngHypergeometric,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r, const int a, const int b, const int c))
_Mkl_Api(int,viRngNegbinomial,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r, const double a, const double b))
_Mkl_Api(int,viRngNegBinomial,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r, const double a, const double b))
_Mkl_Api(int,viRngPoisson,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r, const double a ))
_Mkl_Api(int,viRngPoissonV,(const MKL_INT method, VSLStreamStatePtr stream, const MKL_INT n, float * r, const double * a))
