"""
Since it takes a long time to find the right header lines in MKL,
this script copies just the ones we need into a new file called 'mkl_funcs.py'.
"""

mkl_lines = [o.strip() for o in open('all_cblas').readlines()]
vml_lines = [o.strip() for o in open('all_vml').readlines()]
ipp_lines = [o.strip() for o in open('all_ipps').readlines()]

f = open('mkl_funcs.py', 'w')
print('### AUTO-GENERATED BY get_headers.py ###\n', file=f)
print(f'mkl_lines={mkl_lines}', file=f)
print(f'vml_lines={vml_lines}', file=f)
print(f'ipp_lines={ipp_lines}', file=f)

